name = "redrectorxcz"

compatibility_date = "2025-09-28"

main = ".open-next/worker.js"

[vars]
PROTECT = "7vzxSwpc4Sz/z03rTlgpatg3WNJvyu22GgCzh9XGty4="
SID = '2546738MMC'
OPENNEXT_DISABLE_INCREMENTAL_CACHE = "true"

compatibility_flags = ["nodejs_compat"]

[build.upload]
format = "service-worker"

[build.upload.assets]
directory = ".open-next/assets"
binding   = "ASSETS"

